### ISSUE TITLE
Why Error ?

### ISSUE THREAD

**Issue by SofyanTauridOdeMadi** [MackenzieMolloy/ShopGUIPlus-SellGUI#9]
[15:40:52 INFO]: [ShopGUIPlus Sell GUI] Enabling ShopGUIPlus-SellGUI v1.1.3
[15:40:52 INFO]: [ShopGUIPlus Sell GUI] Your server is running version '1_18_R2'.
[15:40:52 ERROR]: [ShopGUIPlus Sell GUI] Failed to load the 'config.yml' file due to an error:
org.bukkit.configuration.InvalidConfigurationException: Top level is not a Map.
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:106) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.mackenziemolloy.shopguiplus.sellgui.utility.CommentedConfiguration.loadFromString(CommentedConfiguration.java:128) ~[[TUI]-ShopGUIPlus_SellGUI.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.mackenziemolloy.shopguiplus.sellgui.SellGUI.generateFiles(SellGUI.java:94) ~[[TUI]-ShopGUIPlus_SellGUI.jar:?]
        at net.mackenziemolloy.shopguiplus.sellgui.SellGUI.onEnable(SellGUI.java:39) ~[[TUI]-ShopGUIPlus_SellGUI.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:40:52 INFO]: [ShopGUIPlus Sell GUI] *-*
[15:40:52 INFO]: [ShopGUIPlus Sell GUI] ShopGUIPlus SellGUI
[15:40:52 INFO]: [ShopGUIPlus Sell GUI] Made by Mackenzie Molloy
[15:40:52 INFO]: [ShopGUIPlus Sell GUI] *-*

**Comment by SofyanTauridOdeMadi** [comment]
```
#
#     ____  _____ _     _     ____ _   _ ___
#    / ___|| ____| |   | |   / ___| | | |_ _|
#    \___ \|  _| | |   | |  | |  _| | | || |
#     ___) | |___| |___| |__| |_| | |_| || |
#    |____/|_____|_____|_____\____|\___/|___|
#           ( By Mackenzie Molloy )

# Support Discord | https://mackenziemolloy.net/discord

#
# Permissions:
#   - sellgui.use | Access to /sellgui (opens the sellgui)
#   - sellgui.reload | Access to /sellgui reload (reloads configuration)
#   - sellgui.debug | Access to /sellgui dump (dumps server information to a paste)
#

options:
  #
  # 0 - None
  # 1 - Hover message (Adds "receipt_text" to the end of the message)
  #
  receipt_type: 1
  sell_titles: false

  #
  # Whether prices should be rounded to 2 decimal places, or not.
  # This also formats prices with comma separation. IE: 1800 -> 1,800
  #

  rounded_pricing: false

  #
  # Whether trailing zero decimals should be removed (28.0, 28.00, etc --> 28)
  #

  remove_trailing_zeros: false

  #
  # Sounds that are played during certain events
  #

  sounds:
    enabled: true
    error_notifcation: true
    pitch: 1
    volume: 1
    events:
      # If you don't want a certain event to have a sound, just set to an invalid value
      # NOTE: THESE DEFAULT VALUES ARE FOR 1.13+
      open: BLOCK_CHEST_OPEN
      success: ENTITY_VILLAGER_CELEBRATE
      failed: ENTITY_VILLAGER_HURT

  #
  # Action Bar Messages only work on versions 1.9+
  #
  action_bar_msgs: false

  #
  # Only relevent in versions prior to 1.13, basically do you want trialing ":(NUMBER)" on item lists (IE: "STONE:2")
  #

  show_item_damage: true

  #
  # How many rows the GUI will have
  # Min: 1 - Max: 6
  #
  rows: 6

  #
  # Similar to the SGP Item format: (EXAMPLE)
  # 1:
  #   type: dummy <--- Not required, but may become applicable in future updates I make
  #   item:
  #     material: STONE
  #     damage: 1 <--- Only use if you're running 1.12 or below
  #     quantity: 1
  #     name: "&7Cool name"
  #     lore:
  #       - "&7Lore Line 1"
  #       - "&9Lore line 2"
  #       ...and so on
  #   commandsOnClick: (or commandsOnClickConsole)
  #     - "say %PLAYER%"
  #   slot: 1
  #

  decorations: []




messages:
  no_permission: '&b&lTOKO &8&l» &7Anda tidak memiliki izin'
  sellgui_title: '&f&l»&7&l» &8MENU | PENJUALAN &7&l«&f&l«'
  reloaded_config: '&b&lTOKO &8&l» &7File konfigurasi yang dimuat ulang.'
  no_items_sold: '&b&lTOKO &8&l» &7Anda tidak memiliki sesuatu yang bisa dijual.'
  no_items_in_gui: '&b&lTOKO &8&l» &7Anda tidak menempatkan item apa pun di GUI.'
  #
  # {list} - returns a list of sold items
  # {earning} - returns the total amount made
  # {amount} - returns amount of items sold
  #
  items_sold: '&b&lTOKO &8&l» &7Anda menjual &b{list}&7 seharga &b{earning}&7.'
  receipt_text: '&7(DITERIMA)'
  receipt_title: |+
    &f&nDaftar jualan

  #
  # {amount} - returns amount of item
  # {item} - returns item name
  # {price} - returns the selling price of the item
  #
  receipt_item_layout: '&b{amount} x {item} &fSeharga &3{price}'
  #
  # {amount} - returns amount of items sold
  # {earning} - returns the total amount made
  #
  sell_title: '&b&l+ {earning}'
  sell_subtitle: '&7Jual &b&n{amount}&7 item'
  gamemode_not_allowed: '&b&lTOKO &8&l» &7Anda tidak diperbolehkan menggunakan Menu
    penjualan dalam mode &b{gamemode}&7.'
  inventory_full: '&b&lTOKO &8&l» &7Inventaris Anda saat ini penuh, Sisannya telah
    dijatuhkan ke tanah.'
  #
  # {amount} - returns amount of items sold
  # {earning} - returns the total amount made
  #
  action_bar_items_sold: '&b&lTOKO &8&l» &7Anda menjual &b{amount} &7item dalam penjualan
    ini.'
```

**Comment by SofyanTauridOdeMadi** [comment]
My config , Is there something wrong?, because previously I used the default setup, it happened fine

**Comment by MackenzieMolloy** [comment]
Please try re-generating your config.yml by deleting it, and restarting your server.

**Comment by SofyanTauridOdeMadi** [comment]
> Please try re-generating your config.yml by deleting it, and restarting your server.

I've changed the Config to the original, when I changed it it happened like the configuration above

**Comment by SofyanTauridOdeMadi** [comment]
Even though my configuration is like this (https://pastes.dev/oSdQwxH8Ur) and no problem occurs. when my server restart or load this plugin, suddenly the configuration change to like this (https://pastes.dev/I3QyCVLLhW)

**Comment by MackenzieMolloy** [comment]
Please can you join the support discord so that I can provide more immediate support?
https://mackenziemolloy.net/discord
